<a href="https://colab.research.google.com/github/Yogeswari-sri/Data-Cleaning-with-Python-Pandas/blob/main/My_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

#Read a CSV file from Drive
df = pd.read_csv("/content/drive/MyDrive/Python as DA/Employee_data.csv")
df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car,Useless_Col
0,1000,hannah,NaN,finance,$Developer$,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0,NaN
1,1001,ivan,30.0,it,Sr@Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0,remove_me
2,1002,frank,32.0,IT,Intern*,19-04-2023,70k,good,NaN,1,remove_me
3,1003,david,NaN,IT,Data-Scientist,02/14/23,40000,poor,31-10-2025 19:00,NaN,remove_me
4,1004,mike,28.0,finanace,$Developer$,16-Aug-19,60000,NaN,NaN,1,remove_me
...,...,...,...,...,...,...,...,...,...,...,...
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1,NaN
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0,remove_me
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1,remove_me
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0,NaN
204,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No,remove_me

In [4]:
#Displaying the data frame
df

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car,Useless_Col
0,1000,hannah,NaN,finance,$Developer$,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0,NaN
1,1001,ivan,30.0,it,Sr@Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0,remove_me
2,1002,frank,32.0,IT,Intern*,19-04-2023,70k,good,NaN,1,remove_me
3,1003,david,NaN,IT,Data-Scientist,02/14/23,40000,poor,31-10-2025 19:00,NaN,remove_me
4,1004,mike,28.0,finanace,$Developer$,16-Aug-19,60000,NaN,NaN,1,remove_me
...,...,...,...,...,...,...,...,...,...,...,...
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1,NaN
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0,remove_me
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1,remove_me
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0,NaN
204,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No,remove_me

In [5]:
df_safe = df.copy()

Initial Aspect

In [ ]:
# Show first 5 rows of dataset (quick overview of data)
df.head()

In [6]:
df.tail()

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car,Useless_Col
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1,NaN
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0,remove_me
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1,remove_me
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0,NaN
204,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No,remove_me

In [7]:
df.shape

(205, 11)

In [13]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Department', 'Position', 'Joining_Date',
       'Salary', 'Feedback', 'Last_Login_Time', 'Has_Car'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Employee_ID      205 non-null    int64
 1   Name             205 non-null    object
 2   Age              174 non-null    float64
 3   Department       205 non-null    object
 4   Position         205 non-null    object
 5   Joining_Date     205 non-null    object
 6   Salary           188 non-null    object
 7   Feedback         142 non-null    object
 8   Last_Login_Time  150 non-null    object
 9   Has_Car          186 non-null    object
 10  Useless_Col      112 non-null    object
dtypes: float64(1), int64(1), object(9)
memory usage: 17.7+ KB

In [14]:
df.isnull().sum()

Employee_ID         0
Name                0
Age                31
Department          0
Position            0
Joining_Date        0
Salary             16
Feedback           60
Last_Login_Time    55
Has_Car            19
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

# **Data Cleaning and Transformation**

In [9]:
df.drop('Useless_Col', axis=1,inplace=True)

In [12]:
df.duplicated().sum()

np.int64(0)

In [ ]:
#Display Duplicate Rows
df[df.duplicated(keep=False)]

In [11]:
# Remove duplicates
df.drop_duplicates(inplace=True)

In [10]:
df.isnull().sum()

Employee_ID         0
Name                0
Age                31
Department          0
Position            0
Joining_Date        0
Salary             17
Feedback           63
Last_Login_Time    55
Has_Car            19
dtype: int64

step 1 : First column Employee_ID

In [18]:
df['Employee_ID']=df["Employee_ID"].astype(str)

Name column

In [19]:
df["Name"] =df["Name"].str.title().str.strip()

Age column

In [20]:
df['Age'].fillna(df['Age'].median(), inplace=True)
# df["Age"]=df["Age"].fillna(df["Age"].mean())

/tmp/ipykernel_1022/291747684.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)

Department column

In [22]:
df["Department"].unique()

array(['finance', 'it', 'IT', 'finanace', 'HR', 'FINANCE', 'sales',
       'MARKETING', 'hr', 'FINANACE', 'marketing', 'SALES'], dtype=object)

In [21]:
df["Department"].value_counts()

Department
it           26
finance      22
IT           21
HR           21
FINANCE      21
hr           20
sales        15
marketing    14
SALES        12
FINANACE     12
MARKETING    10
finanace      6
Name: count, dtype: int64

In [23]:
# Upper conversion
df["Department"] = df["Department"].str.upper()

In [24]:
#Replace multiple values in a column
df['Department'].replace({
    'FINANACE': 'Finance',
    'MARKETING': 'Marketing',
    'SALES': 'Sales'
}, inplace=True)

/tmp/ipykernel_1022/1786196148.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Department'].replace({

Position column

In [25]:
df["Position"].unique()

array(['$Developer$', 'Sr@Analyst', 'Intern*', 'Data-Scientist',
       '@Manager', '!Clerk', '#Analyst'], dtype=object)

In [26]:
df["Position"].value_counts()

Position
Data-Scientist    32
@Manager          31
$Developer$       29
Intern*           28
Sr@Analyst        28
!Clerk            28
#Analyst          24
Name: count, dtype: int64

In [27]:
# Symbol conversion using Regular Expression
df["Position"] =df["Position"].str.replace(r'[^a-zA-Z]'," ",regex= True).str.strip()

Salary column

In [28]:
df["Salary"].unique()

array(['70k', '45,500', '40000', '60000', nan, '65,000', '55000', '50000'],
      dtype=object)

In [30]:
df["Salary"].value_counts()

Salary
40000     33
60000     31
45,500    30
55000     27
70000     23
65,000    23
50000     17
Name: count, dtype: int64

In [ ]:
# If duplicate values is there then only used this dropna
#df["Salary"].value_counts(dropna = False)

In [29]:
#Replace "70k" to "70000"
df["Salary"] = df['Salary'].str. replace("70k","70000")

In [33]:
# Remove only commas using Regular expression
df["Salary"] = df["Salary"].replace(r',', '', regex=True)

# Convert to float
df["Salary"] = df["Salary"].astype(float)

In [34]:
df

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,Hannah,30.0,FINANCE,Developer,"Sep 16, 2023",70000.0,poor,11-11-2025 22:00,0
1,1001,Ivan,30.0,IT,Sr Analyst,29-Aug-22,45500.0,excellent,07-11-2025 05:00,0
2,1002,Frank,32.0,IT,Intern,19-04-2023,70000.0,good,NaN,1
3,1003,David,30.0,IT,Data Scientist,02/14/23,40000.0,poor,31-10-2025 19:00,NaN
4,1004,Mike,28.0,Finance,Developer,16-Aug-19,60000.0,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...
195,1195,Nina,26.0,Marketing,Sr Analyst,07-07-2020,60000.0,poor,07-11-2025 09:00,Yes
196,1196,Paula,26.0,Finance,Analyst,12-05-2021,45500.0,NaN,08-11-2025 16:00,0
197,1197,Alice,30.0,FINANCE,Data Scientist,14-02-2022,65000.0,good,11-11-2025 22:00,0
198,1198,Mike,32.0,IT,Clerk,02/15/21,45500.0,average,NaN,1
199,1199,Kevin,28.0,IT,Developer,15-Jul-20,40000.0,average,03-11-2025 16:00,Yes

In [35]:
# Hierarchical imputation
# Level 1: Department + Position mean
dept_pos_mean = df.groupby(['Department','Position'])['Salary'].transform('median')

# # # # Level 2: Department mean
dept_mean = df.groupby('Department')['Salary'].transform('mean')

# # # Level 3: Overall mean
overall_mean = df['Salary'].mean()

# Hierarchical imputation
df['Salary'] = (df['Salary'].fillna(dept_pos_mean).fillna(dept_mean).fillna(overall_mean))

Feedback column

In [36]:
df["Feedback"].unique()

array(['poor', 'excellent', 'good', nan, 'average', '?'], dtype=object)

In [37]:
df["Feedback"].value_counts()

Feedback
poor         31
good         29
average      29
?            26
excellent    25
Name: count, dtype: int64

In [40]:
# Remove symbol using Regular expression
df["Feedback"] = df["Feedback"].replace(r'"?",''', regex=True).str.title()

In [41]:
df["Feedback"] = df['Feedback'].fillna("Average")

Has_car

In [42]:
df["Has_Car"].unique()

array(['0', '1', nan, 'No', 'Yes'], dtype=object)

In [43]:
df["Has_Car"].value_counts()

Has_Car
1      77
0      57
No     27
Yes    20
Name: count, dtype: int64

In [44]:
df['Has_Car'].replace({
    '0': 'No',
    '1': 'Yes'
}, inplace=True)

/tmp/ipykernel_1022/1435213368.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Has_Car'].replace({

In [45]:
df["Has_Car"] = df['Has_Car'].fillna("No")

In [46]:
df

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,Hannah,30.0,FINANCE,Developer,"Sep 16, 2023",70000.0,Poor,11-11-2025 22:00,No
1,1001,Ivan,30.0,IT,Sr Analyst,29-Aug-22,45500.0,Excellent,07-11-2025 05:00,No
2,1002,Frank,32.0,IT,Intern,19-04-2023,70000.0,Good,NaN,Yes
3,1003,David,30.0,IT,Data Scientist,02/14/23,40000.0,Poor,31-10-2025 19:00,No
4,1004,Mike,28.0,Finance,Developer,16-Aug-19,60000.0,Average,NaN,Yes
...,...,...,...,...,...,...,...,...,...,...
195,1195,Nina,26.0,Marketing,Sr Analyst,07-07-2020,60000.0,Poor,07-11-2025 09:00,Yes
196,1196,Paula,26.0,Finance,Analyst,12-05-2021,45500.0,Average,08-11-2025 16:00,No
197,1197,Alice,30.0,FINANCE,Data Scientist,14-02-2022,65000.0,Good,11-11-2025 22:00,No
198,1198,Mike,32.0,IT,Clerk,02/15/21,45500.0,Average,NaN,Yes
199,1199,Kevin,28.0,IT,Developer,15-Jul-20,40000.0,Average,03-11-2025 16:00,Yes

**Date and time**

In [48]:
df.dtypes

Employee_ID         object
Name                object
Age                float64
Department          object
Position            object
Joining_Date        object
Salary             float64
Feedback            object
Last_Login_Time     object
Has_Car             object
dtype: object

In [49]:
df.isnull().sum()

Employee_ID         0
Name                0
Age                 0
Department          0
Position            0
Joining_Date        0
Salary              0
Feedback            0
Last_Login_Time    55
Has_Car             0
dtype: int64

Joining_Date

In [50]:
import pandas as pd
import datetime as dt

In [51]:
df['Joining_Date'] = pd.to_datetime(df['Joining_Date'],format="mixed",errors='coerce',dayfirst=True)

In [52]:
df

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,Hannah,30.0,FINANCE,Developer,2023-09-16,70000.0,Poor,11-11-2025 22:00,No
1,1001,Ivan,30.0,IT,Sr Analyst,2022-08-29,45500.0,Excellent,07-11-2025 05:00,No
2,1002,Frank,32.0,IT,Intern,2023-04-19,70000.0,Good,NaN,Yes
3,1003,David,30.0,IT,Data Scientist,2023-02-14,40000.0,Poor,31-10-2025 19:00,No
4,1004,Mike,28.0,Finance,Developer,2019-08-16,60000.0,Average,NaN,Yes
...,...,...,...,...,...,...,...,...,...,...
195,1195,Nina,26.0,Marketing,Sr Analyst,2020-07-07,60000.0,Poor,07-11-2025 09:00,Yes
196,1196,Paula,26.0,Finance,Analyst,2021-05-12,45500.0,Average,08-11-2025 16:00,No
197,1197,Alice,30.0,FINANCE,Data Scientist,2022-02-14,65000.0,Good,11-11-2025 22:00,No
198,1198,Mike,32.0,IT,Clerk,2021-02-15,45500.0,Average,NaN,Yes
199,1199,Kevin,28.0,IT,Developer,2020-07-15,40000.0,Average,03-11-2025 16:00,Yes

Last_Login_Time

In [54]:
df["Last_Login_Time"].unique()

array(['11-11-2025 22:00', '07-11-2025 05:00', nan, '31-10-2025 19:00',
       '11-11-2025 19:00', '31-10-2025 11:00', '02-11-2025 21:00',
       '12-11-2025 07:00', '09-11-2025 01:00', '05-11-2025 04:00',
       '07-11-2025 20:00', '05-11-2025 06:00', '04-11-2025 19:00',
       '06-11-2025 19:00', '02-11-2025 15:00', '04-11-2025 09:00',
       '04-11-2025 17:00', '10-11-2025 23:00', '10-11-2025 18:00',
       '10-11-2025 07:00', '02-11-2025 18:00', '04-11-2025 16:00',
       '06-11-2025 18:00', '10-11-2025 22:00', '08-11-2025 19:00',
       '31-10-2025 13:00', '11-11-2025 06:00', '06-11-2025 17:00',
       '31-10-2025 08:00', '05-11-2025 17:00', '02-11-2025 16:00',
       '31-10-2025 23:00', '30-10-2025 23:00', '31-10-2025 00:00',
       '07-11-2025 18:00', '09-11-2025 12:00', '10-11-2025 12:00',
       '10-11-2025 02:00', '11-11-2025 02:00', '02-11-2025 11:00',
       '31-10-2025 15:00', '12-11-2025 05:00', '10-11-2025 00:00',
       '01-11-2025 00:00', '06-11-2025 20:00', '08-11-2025 15:00',
       '10-11-2025 04:00', '06-11-2025 02:00', '01-11-2025 15:00',
       '09-11-2025 04:00', '09-11-2025 00:00', '01-11-2025 03:00',
       '05-11-2025 13:00', '10-11-2025 01:00', '05-11-2025 21:00',
       '01-11-2025 02:00', '09-11-2025 17:00', '31-10-2025 17:00',
       '03-11-2025 10:00', '31-10-2025 22:00', '08-11-2025 04:00',
       '03-11-2025 22:00', '04-11-2025 11:00', '01-11-2025 10:00',
       '07-11-2025 04:00', '07-11-2025 13:00', '01-11-2025 11:00',
       '07-11-2025 21:00', '31-10-2025 06:00', '07-11-2025 06:00',
       '03-11-2025 18:00', '11-11-2025 07:00', '10-11-2025 08:00',
       '10-11-2025 03:00', '10-11-2025 20:00', '10-11-2025 11:00',
       '07-11-2025 09:00', '11-11-2025 04:00', '31-10-2025 14:00',
       '02-11-2025 01:00', '11-11-2025 05:00', '31-10-2025 21:00',
       '11-11-2025 09:00', '01-11-2025 17:00', '10-11-2025 17:00',
       '07-11-2025 10:00', '31-10-2025 07:00', '08-11-2025 02:00',
       '05-11-2025 18:00', '06-11-2025 01:00', '10-11-2025 21:00',
       '31-10-2025 10:00', '05-11-2025 00:00', '09-11-2025 02:00',
       '31-10-2025 20:00', '01-11-2025 04:00', '10-11-2025 05:00',
       '09-11-2025 14:00', '09-11-2025 03:00', '07-11-2025 23:00',
       '07-11-2025 02:00', '11-11-2025 08:00', '06-11-2025 13:00',
       '09-11-2025 16:00', '03-11-2025 08:00', '09-11-2025 06:00',
       '04-11-2025 13:00', '09-11-2025 07:00', '11-11-2025 13:00',
       '11-11-2025 14:00', '10-11-2025 06:00', '31-10-2025 12:00',
       '08-11-2025 16:00', '03-11-2025 16:00'], dtype=object)

In [55]:
df["Last_Login_Time"].value_counts()

Last_Login_Time
07-11-2025 05:00    3
10-11-2025 23:00    3
02-11-2025 18:00    3
03-11-2025 10:00    3
05-11-2025 04:00    2
                   ..
11-11-2025 14:00    1
10-11-2025 06:00    1
31-10-2025 12:00    1
08-11-2025 16:00    1
03-11-2025 16:00    1
Name: count, Length: 113, dtype: int64

In [61]:
# Changing Data Types (Because Object we want DateTime so...)
df["Last_Login_Time"]=pd.to_datetime(df["Last_Login_Time"],errors="coerce",dayfirst=True)

print(df["Last_Login_Time"].dtype)

datetime64[ns]

In [57]:
df['Last_Login_Time'] = pd.to_datetime(df['Last_Login_Time'],format="mixed",errors='coerce',dayfirst=True)
df

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,Hannah,30.0,FINANCE,Developer,2023-09-16,70000.0,Poor,2025-11-11 22:00:00,No
1,1001,Ivan,30.0,IT,Sr Analyst,2022-08-29,45500.0,Excellent,2025-11-07 05:00:00,No
2,1002,Frank,32.0,IT,Intern,2023-04-19,70000.0,Good,NaT,Yes
3,1003,David,30.0,IT,Data Scientist,2023-02-14,40000.0,Poor,2025-10-31 19:00:00,No
4,1004,Mike,28.0,Finance,Developer,2019-08-16,60000.0,Average,NaT,Yes
...,...,...,...,...,...,...,...,...,...,...
195,1195,Nina,26.0,Marketing,Sr Analyst,2020-07-07,60000.0,Poor,2025-11-07 09:00:00,Yes
196,1196,Paula,26.0,Finance,Analyst,2021-05-12,45500.0,Average,2025-11-08 16:00:00,No
197,1197,Alice,30.0,FINANCE,Data Scientist,2022-02-14,65000.0,Good,2025-11-11 22:00:00,No
198,1198,Mike,32.0,IT,Clerk,2021-02-15,45500.0,Average,NaT,Yes
199,1199,Kevin,28.0,IT,Developer,2020-07-15,40000.0,Average,2025-11-03 16:00:00,Yes

In [62]:
# NaT replace using Fillna
df["Last_Login_Time"]=df['Last_Login_Time'].fillna(df['Last_Login_Time'].mode()[0])

# **Feature Engineering**

In [ ]:
df

In [63]:
df["Join_Month"]=df['Joining_Date'].dt.month

In [66]:
df["Login_Time"]=df["Last_Login_Time"].dt.time
df

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car,Join_Month,Login_Time
0,1000,Hannah,30.0,FINANCE,Developer,2023-09-16,70000.0,Poor,2025-11-11 22:00:00,No,9,22:00:00
1,1001,Ivan,30.0,IT,Sr Analyst,2022-08-29,45500.0,Excellent,2025-11-07 05:00:00,No,8,05:00:00
2,1002,Frank,32.0,IT,Intern,2023-04-19,70000.0,Good,2025-11-02 18:00:00,Yes,4,18:00:00
3,1003,David,30.0,IT,Data Scientist,2023-02-14,40000.0,Poor,2025-10-31 19:00:00,No,2,19:00:00
4,1004,Mike,28.0,Finance,Developer,2019-08-16,60000.0,Average,2025-11-02 18:00:00,Yes,8,18:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
195,1195,Nina,26.0,Marketing,Sr Analyst,2020-07-07,60000.0,Poor,2025-11-07 09:00:00,Yes,7,09:00:00
196,1196,Paula,26.0,Finance,Analyst,2021-05-12,45500.0,Average,2025-11-08 16:00:00,No,5,16:00:00
197,1197,Alice,30.0,FINANCE,Data Scientist,2022-02-14,65000.0,Good,2025-11-11 22:00:00,No,2,22:00:00
198,1198,Mike,32.0,IT,Clerk,2021-02-15,45500.0,Average,2025-11-02 18:00:00,Yes,2,18:00:00
199,1199,Kevin,28.0,IT,Developer,2020-07-15,40000.0,Average,2025-11-03 16:00:00,Yes,7,16:00:00